spring.application.name=convert_http_to_https

#server.port=8083

server.port=8443

server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=pitafi
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=springboot-https